from video_converter.config import *

FILES_ROOT = "user_files/"
UPLOADS = "uploads/"
COMPLETED = "completed/"
USER_ROOT = FILES_ROOT + "{}/"
UPLOADS_DIRECTORY = USER_ROOT + UPLOADS
COMPLETED_DIRECTORY = USER_ROOT + COMPLETED
FILE_NAME_SUFFIX = "({}bps).mp4"
ZIP_FILE = COMPLETED_DIRECTORY + "/converted_files.zip"
HOME_URL = LOCAL_URL if DEV_MODE else PUBLIC_URL
ONE_HOUR = 3600
SESSION_DURATION = ONE_HOUR * 8
SESSION_DAEMON_INTERVAL = 10
